apiVersion: v1
kind: PersistentVolume
metadata:
  name: scm-storage
spec:
  storageClassName: hostpath
  hostPath:
    path: /storage/data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scm-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi