apiVersion: v1
kind: PersistentVolume
metadata:
  name: scm-storage
spec:
  storageClassName: manual
  hostPath:
    path: /scm-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scm-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual