apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-queue
  labels:
    app: scm-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm-queue
  template:
    metadata:
      labels:
        app: scm-queue
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: scm-queue
spec:
  selector:
    app: scm-queue
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: http